# Предложения
## Создать новое предложение
POST http://localhost:4000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmxhZCIsImVtYWlsIjoidmxhZEB2LnJ1IiwiaWQiOiI2NjYyYWE5MjM4OWFmY2EwMWQyYzZlODAiLCJpYXQiOjE3MTgzNjc0MjcsImV4cCI6MTcxODQ1MzgyN30.2XdK4VZbgM000o9SsELixy6gwqEVTsiHe9Gg0OgK4OI

{
"denomination": "Hotel Volgograd",
  "descriptionOffer": "This is hotel lacated in the city center near to the square of stars.",
  "city": "Paris",
  "previewImage": "img/room.jpg",
  "photosHousing": [
    "photo-1.jpg",
    "photo-2.jpg",
    "photo-3.jpg",
    "photo-4.jpg",
    "photo-5.jpg",
    "photo-6.jpg"
  ],
  "premium": false,
  "favorites": false,
  "typeHousing": "hotel",
  "numberRooms": 6,
  "numberGuests": 9,
  "rentPrice": 12752,
  "comforts": ["Baby seat","Washer","Towels","Fridge"],
  "coordinates": {
    "latitude": 52.370216,
    "longitude": 4.895168
  }
}

###

## Редактирование предложения
PATCH  http://localhost:4000/offers/redaction/665f059114983998026a1dfe HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmxhZCIsImVtYWlsIjoidmxhZEB2LnJ1IiwiaWQiOiI2NjVmMDMyZDE0OTgzOTk4MDI2YTFkZjkiLCJpYXQiOjE3MTc1NzU3OTcsImV4cCI6MTcxNzU3NjM5N30.2FRR27L1Zg0HxgtJULBLMhLwLLyxPtLEcB_b9kfTtF4

{
"denomination": "Hotel Volgograd Star",
  "descriptionOffer": "This is hotel lacated in the city center near to the square of stars.",
  "datePublication": "2024-05-29T21:00:00.000Z",
  "city": "Paris",
  "previewImage": "img/room.jpg",
  "photosHousing": [
    "photo-1.jpg",
    "photo-2.jpg",
    "photo-3.jpg",
    "photo-4.jpg",
    "photo-5.jpg",
    "photo-6.jpg"
  ],
  "premium": false,
  "favorites": false,
  "typeHousing": "hotel",
  "numberRooms": 6,
  "numberGuests": 9,
  "rentPrice": 12752,
  "comforts": ["Baby seat","Washer","Towels","Fridge"],
  "authorOfOffer": {
    "name": "Vlad",
    "email": "vlad@v.ru",
    "avatarUser": "fadfaa3d-04a2-401e-809c-46c26145bec4.png",
    "typeUser": "ordinary"
  },
  "coordinates": {
    "latitude": 52.370216,
    "longitude": 4.895168
  }
}

###

## Удаление предложения
DELETE http://localhost:4000/offers/delete/664af503f4a08beb5f8eab89 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lsZSIsImVtYWlsIjoiS2lsZUAyNC5ydSIsImlkIjoiNjY0ZjY1OTc1OGZjNzc3MGU2ODZiODg5IiwiaWF0IjoxNzE2OTEyNzQwLCJleHAiOjE3MTcwODU1NDB9.QgVOnhw_7oODCIxaJvkSj_Rvq5rYyU5UeivWUNctMSs

###

## Получение списка предложений
GET http://localhost:4000/offers/list?count=10 HTTP/1.1
Content-Type: application/json

###

## Получение детальной информации по предложению
GET http://localhost:4000/offers/offer/66408fea33d03531e7967faf HTTP/1.1
Content-Type: application/json

###

## Получение премиальных предложений для города
GET http://localhost:4000/offers/premium?nameCity=Brussels HTTP/1.1
Content-Type: application/json
