# Предложения
## Создать новое предложение
POST http://localhost:4000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS29sZSIsImVtYWlsIjoiS29sZUBrb2wucnUiLCJpZCI6IjY2NTZlMzFmNjZkNjg4ZTQ5NDU0MTkwNiIsImlhdCI6MTcxNjk3ODg4NSwiZXhwIjoxNzE2OTc5NDg1fQ.nG-1KYrnPS5pIoPVMXiSB-ipu6q_ZjZXLxNLvh4k8kM

{
"denomination": "Birdie Village best hotel",
  "descriptionOffer": "This is hotel lacated in the city center near to the square of stars.",
  "datePublication": "2024-05-29T21:00:00.000Z",
  "city": "Amsterdam",
  "previewImage": "photo-room.jpg",
  "photosHousing": [
    "photo-1.jpg",
    "photo-2.jpg",
    "photo-3.jpg",
    "photo-4.jpg",
    "photo-5.jpg",
    "photo-6.jpg"
  ],
  "premium": false,
  "favorites": false,
  "typeHousing": "hotel",
  "numberRooms": 6,
  "numberGuests": 9,
  "rentPrice": 12752,
  "comforts": ["Baby seat","Washer","Towels","Fridge"],
  "authorOfOffer": {
    "name": "Kole",
    "email": "Kole@kol.ru",
    "avatarUser": "Kole34.jpg",
    "typeUser": "ordinary"
  },
  "coordinates": {
    "latitude": 52.370216,
    "longitude": 4.895168
  }
}

###

## Редактирование предложения
PATCH  http://localhost:4000/offers/redaction/665609715a44c3285df4ea44 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lsZSIsImVtYWlsIjoiS2lsZUAyNC5ydSIsImlkIjoiNjY0ZjY1OTc1OGZjNzc3MGU2ODZiODg5IiwiaWF0IjoxNzE2OTEyNzQwLCJleHAiOjE3MTcwODU1NDB9.QgVOnhw_7oODCIxaJvkSj_Rvq5rYyU5UeivWUNctMSs

{
"denomination": "Rostov big Star hotel",
  "descriptionOffer": "This is hotel lacated in the city center near to the square of stars.",
  "datePublication": "2024-05-04T21:00:00.000Z",
  "city": "Paris",
  "previewImage": "photo-room.jpg",
  "photosHousing": [
    "photo-1.jpg",
    "photo-2.jpg",
    "photo-3.jpg",
    "photo-4.jpg",
    "photo-5.jpg",
    "photo-6.jpg"
  ],
  "premium": false,
  "favorites": false,
  "typeHousing": "hotel",
  "numberRooms": 6,
  "numberGuests": 9,
  "rentPrice": 12752,
  "comforts": ["Washer","Towels","Fridge"],
  "authorOfOffer": {
    "name": "Alexs",
    "email": "Kile@24.ru",
    "avatarUser": "yan34v.jpg",
    "typeUser": "ordinary"
  },
  "coordinates": {
    "latitude": 52.370216,
    "longitude": 4.895168
  }
}

###

## Удаление предложения
DELETE http://localhost:4000/offers/delete/664af503f4a08beb5f8eab89 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2lsZSIsImVtYWlsIjoiS2lsZUAyNC5ydSIsImlkIjoiNjY0ZjY1OTc1OGZjNzc3MGU2ODZiODg5IiwiaWF0IjoxNzE2OTEyNzQwLCJleHAiOjE3MTcwODU1NDB9.QgVOnhw_7oODCIxaJvkSj_Rvq5rYyU5UeivWUNctMSs

###

## Получение списка предложений
GET http://localhost:4000/offers/list?count=4 HTTP/1.1
Content-Type: application/json

###

## Получение детальной информации по предложению
GET http://localhost:4000/offers/offer/66408fea33d03531e7967faf HTTP/1.1
Content-Type: application/json

###

## Получение премиальных предложений для города
GET http://localhost:4000/offers/premium/Brussels HTTP/1.1
Content-Type: application/json
