# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Vlad",
  "email": "vlad@v",
  "password": "Volga34",
  "typeUser": "ordinary"
}

###
## Вход в закрытую часть приложения

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "vlad@v.ru",
  "password": "1984V.V"
}

###
## Отправить изображение

POST http://localhost:4000/users/6662aa92389afca01d2c6e80/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-angelina.jpg"
Content-Type: image/png

< C:\Users\User\Desktop\1861971-six-cities-1\markup\img\avatar-angelina.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Проверка состояния пользователя

GET  http://localhost:4000/users/authenticate HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVmxhZCIsImVtYWlsIjoidmxhZEB2LnJ1IiwiaWQiOiI2NjVlZjBjNzIxODZhZDUwMzI3MTJmYWMiLCJpYXQiOjE3MTc1MDIyNzgsImV4cCI6MTcxNzUwMjg3OH0.0rLVnOtAykvnrJ1xFyTTW6E8UAVruNvMOKUTbQzcehw
